# Generated by Django 5.2.1 on 2025-05-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialist_name', models.CharField(max_length=50, verbose_name='Name')),
                ('describing', models.TextField(verbose_name='Describing')),
                ('requirements', models.TextField(verbose_name='Requirements')),
                ('salary', models.CharField(max_length=100, verbose_name='Salary')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
            },
        ),
    ]
