# Generated by Django 5.2.1 on 2025-05-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promocodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Name')),
                ('full_text', models.TextField(verbose_name='Question full text')),
                ('date', models.DateTimeField(verbose_name='Expire date')),
            ],
            options={
                'verbose_name': 'Promo-code',
                'verbose_name_plural': 'Promo-codes',
            },
        ),
    ]
