# Generated by Django 4.2.23 on 2025-09-13 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partners',
            options={'verbose_name': 'Partner', 'verbose_name_plural': 'Partners'},
        ),
    ]
