# Generated by Django 5.2.1 on 2025-05-26 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='extras',
        ),
    ]
